/*
Navicat MySQL Data Transfer

Source Server         : 172.20.5.239
Source Server Version : 50547
Source Host           : 172.20.5.239:3306
Source Database       : scm_test

Target Server Type    : MYSQL
Target Server Version : 50547
File Encoding         : 65001

Date: 2018-06-24 23:16:51
*/


-- ----------------------------
-- Records of v60_settings
-- ----------------------------
INSERT INTO `v60_settings` VALUES ('1', 'net_connect_setting', '网络与连接', '系统设置', '设置入口页', '', '0', '0', '2', '1', '系统设置主大块 - 网络与连接', '<SettingModual modualName=\"net_connect_setting\" modualIcon=\"main_setting_connect\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.ConnectSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('2', 'picture_sound_setting', '图像与声音', '系统设置', '设置入口页', '', '0', '0', '3', '1', '系统设置主大块 - 图像与声音', '<SettingModual modualName=\"picture_sound_setting\" modualIcon=\"main_setting_picturesound\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.PictureSoundSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('3', 'general_setting', '通用设置', '系统设置', '设置入口页', '', '0', '0', '4', '1', '系统设置主大块 - 通用设置', '<SettingModual modualName=\"general_setting\" modualIcon=\"main_setting_general\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.GeneralSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('4', 'account_payment_setting', '账户与支付', '系统设置', '设置入口页', '', '0', '0', '5', '1', '系统设置主大块 - 账户与支付', '<SettingModual modualName=\"account_payment_setting\" modualIcon=\"main_setting_accountpayment\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.AccountPaymentSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('5', 'system_upgrade_setting', '升级', '系统设置', '设置入口页', '', '0', '0', '6', '1', '系统设置主大块 - 升级', '<SettingModual modualName=\"system_upgrade_setting\" modualIcon=\"main_setting_upgrade\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.SystemUpgradeSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('6', 'about_tv_setting', '关于本机', '系统设置', '设置入口页', '', '0', '0', '1', '1', '系统设置主大块 - 关于本机', '<SettingModual modualName=\"about_tv_setting\" modualIcon=\"main_setting_about_tv\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.AboutTvSetting\"/>', 'setting_main.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('7', 'SettingGuide_pageName_NET', '网络连接', '系统设置', '开机引导', '', '0', '0', '1', '1', '开机引导的选择开关 - 网络连接页', '<SettingGuide pageName=\"NET\" className = \"com.tianci.setting.guidesetting.SkyGuideNetActivity\" stepText=\"guide_connect\" isCanSkipNet=\"false\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('8', 'SettingGuide_pageName_AWARD', '激活电视', '系统设置', '开机引导', '', '0', '0', '2', '1', '开机引导的选择开关 - 激活电视页', '<SettingGuide pageName=\"AWARD\" className = \"com.tianci.setting.guidesetting.SkyGuideAward\" stepText=\"guide_active\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('9', 'SettingGuide_pageName_ACCOUNT', '默认配置', '系统设置', '开机引导', '', '0', '0', '3', '1', '开机引导的选择开关 - 默认配置页，不用管', '<SettingGuide pageName=\"ACCOUNT\" className = \"com.tianci.setting.guidesetting.SkyGuideAccount\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('10', 'SettingGuide_pageName_QR', '酷开会员', '系统设置', '开机引导', '', '0', '0', '4', '1', '开机引导的选择开关 - 酷开会员页', '<SettingGuide pageName=\"QR\" className = \"com.tianci.setting.guidesetting.SkyGuideQRActivity\" stepText=\"guide_coocaa_member\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('11', 'SettingGuide_pageName_BT', '蓝牙配对', '系统设置', '开机引导', '', '0', '0', '5', '1', '开机引导的选择开关 - 标配蓝牙遥控器配对', '<SettingGuide pageName=\"BT\" className = \"com.tianci.setting.connectsetting.btonekey.OneKeyActivity\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('12', 'SKY_CFG_TV_NET_WIFI', '无线网络', '系统设置', '网络与连接', '', '0', '0', '1', '1', '系统设置-网络与连接XML配置 - 无线网络', '<SettingModual modualName=\"SKY_CFG_TV_NET_WIFI\" type=\"TYPE_WIFI\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('13', 'SKY_CFG_TV_NET_ETHERNET', '有线网络', '系统设置', '网络与连接', '', '0', '0', '2', '1', '系统设置-网络与连接XML配置 - 有线网络', '<SettingModual modualName=\"SKY_CFG_TV_NET_ETHERNET\" type=\"TYPE_ETHERNET\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('14', 'SKY_CFG_TV_NET_WIFI_HOTSPOT', '热点', '系统设置', '网络与连接', '', '0', '0', '3', '1', '系统设置-网络与连接XML配置 - 热点', '<SettingModual modualName=\"SKY_CFG_TV_NET_WIFI_HOTSPOT\" type=\"TYPE_WIFI_HOSTSPOT\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('15', 'SKY_CFG_TV_BLUETOOTH', '内置蓝牙模块', '系统设置', '网络与连接', '', '0', '0', '4', '1', '系统设置-网络与连接XML配置 - 内置蓝牙模块', '<SettingModual modualName=\"SKY_CFG_TV_BLUETOOTH\" type=\"TYPE_BLUETOOTH\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('16', 'SKY_CFG_TV_BLUETOOTH_useDongle', '内置蓝牙dongle', '系统设置', '网络与连接', '', '0', '0', '5', '1', '系统设置-网络与连接XML配置 - 内置蓝牙dongle', '<SettingModual modualName=\"SKY_CFG_TV_BLUETOOTH\" type=\"TYPE_BLUETOOTH\" params=\"useDongle\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v60_settings` VALUES ('17', 'SKY_SYSTEM_ENV_SLEEP_TIMER', '睡眠时间', '系统设置', '通用设置', '个性化设置', '0', '0', '1', '1', '系统设置-通用- - 睡眠时间：即定时关机', '<SettingItem name=\"SKY_SYSTEM_ENV_SLEEP_TIMER\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v60_settings` VALUES ('18', 'SKY_SYSTEM_ENV_START_SCREEN_SAVER_MODE', '屏保时间', '系统设置', '通用设置', '个性化设置', '0', '0', '2', '1', '系统设置-通用- - 屏保时间，有屏保的默认配置，OLED不配置此项，OLED默认2分钟执行屏保', '<SettingItem name=\"SKY_SYSTEM_ENV_START_SCREEN_SAVER_MODE\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v60_settings` VALUES ('19', 'SKY_CFG_TV_TVNAME', '本机名称', '系统设置', '通用设置', '个性化设置', '0', '0', '3', '1', '系统设置-通用- - 本机名称', '<SettingItem name=\"SKY_CFG_TV_TVNAME\" description=\"SKY_CFG_TV_TVNAME_DESCRIPTION\" from=\"Setting\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.PersonallySetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v60_settings` VALUES ('20', 'SKY_CFG_TV_LANGUAGE', '语言设置', '系统设置', '通用设置', '系统设置', '0', '0', '1', '1', '系统设置-通用- - 语言设置，通用', '<SettingItem name=\"SKY_CFG_TV_LANGUAGE\" from=\"Setting\" type=\"TYPE_INFO\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.GeneralSystemSetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('21', 'SKY_CFG_TV_SWITCH_INPUT_METHOD', '输入法', '系统设置', '通用设置', '系统设置', '0', '0', '2', '1', '系统设置-通用- - 输入法，通用', '<SettingItem name=\"SKY_CFG_TV_SWITCH_INPUT_METHOD\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('22', 'SKY_SYSTEM_ENV_BOOT_START_HOME_PAGE', '开机启动主页', '系统设置', '通用设置', '系统设置', '0', '0', '3', '1', '系统设置-通用- - 开机启动主页，所有产品', '<SettingItem name=\"SKY_SYSTEM_ENV_BOOT_START_HOME_PAGE\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('23', 'SKY_CFG_TV_BOOT_SOURCE', '开机通道', '系统设置', '通用设置', '系统设置', '0', '0', '4', '1', '系统设置-通用- - 开机通道', '<SettingItem name=\"SKY_CFG_TV_BOOT_SOURCE\" from=\"TV\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('24', 'SKY_CFG_TV_ONE_KEY_ACTION', '一键直达', '系统设置', '通用设置', '系统设置', '0', '0', '5', '1', '系统设置-通用- - 一键直达', '<SettingItem name=\"SKY_CFG_TV_ONE_KEY_ACTION\" description=\"SKY_CFG_TV_ONE_KEY_ACTION_DESCRIPTION\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.PersonallySetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('25', 'SKY_SYSTEM_ENV_INTERACTION_SWITCH', '互动开关', '系统设置', '通用设置', '系统设置', '0', '0', '6', '1', '系统设置-通用- - 互动开关，酷云勾正之类的可配置', '<SettingItem name=\"SKY_SYSTEM_ENV_INTERACTION_SWITCH\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('26', 'SKY_CFG_TV_SET_TOUCH_CONTROL_SWITCH', '触控开关', '系统设置', '通用设置', '系统设置', '0', '0', '7', '1', '系统设置-通用- - 触控开关', '<SettingItem name=\"SKY_CFG_TV_SET_TOUCH_CONTROL_SWITCH\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('27', 'SKY_CFG_TV_EDID', 'EDID开关', '系统设置', '通用设置', '系统设置', '0', '0', '8', '1', '系统设置-通用- - EDID开关', '<SettingItem name=\"SKY_CFG_TV_EDID\" from=\"Setting\" type=\"TYPE_INFO\" description=\"SKY_CFG_TV_EDID_DESCRIPTION\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.GeneralSystemSetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('28', 'SKY_CFG_TV_INDICATOR_LIGHT_AUTO_OFF_SWITCH', '指示灯勿扰开关', '系统设置', '通用设置', '系统设置', '0', '0', '9', '1', '系统设置-通用- - 指示灯勿扰开关', '<SettingItem name=\"SKY_CFG_TV_INDICATOR_LIGHT_AUTO_OFF_SWITCH\" description=\"SKY_CFG_TV_INDICATOR_LIGHT_AUTO_OFF_SWITCH_DESCRIPTION\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v60_settings` VALUES ('29', 'SKY_CFG_TV_INSTALL_UNKNOWN_SOURCE_APP', '未知来源', '系统设置', '通用设置', '位置与安全', '0', '0', '1', '1', '系统设置-通用- - 未知来源', '<SettingItem name=\"SKY_CFG_TV_INSTALL_UNKNOWN_SOURCE_APP\" description=\"SKY_CFG_TV_INSTALL_UNKNOWN_SOURCE_APP_DESCRIPTION\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_LOCATION_SECURITY', '');
INSERT INTO `v60_settings` VALUES ('30', 'SKY_CFG_TV_RECOVERY', '恢复出厂设置', '系统设置', '通用设置', '位置与安全', '0', '0', '2', '1', '系统设置-通用- - 恢复出厂设置', '<SettingItem name=\"SKY_CFG_TV_RECOVERY\" type=\"TYPE_DIALOG\" description=\"SKY_CFG_TV_RECOVERY_DESCRIPTION\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_LOCATION_SECURITY', '');
INSERT INTO `v60_settings` VALUES ('31', 'SOURCE_MY_APPS', '我的应用', '信号源工具箱', '快捷功能', '', '0', '0', '1', '1', '信号源工具箱-选择开关 - 我的应用', '<SourceQuickItem itemName=\"SOURCE_MY_APPS\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v60_settings` VALUES ('32', 'SOURCE_LOCAL_MEDIA', '本地媒体', '信号源工具箱', '快捷功能', '', '0', '0', '2', '1', '信号源工具箱-选择开关 - 本地媒体', '<SourceQuickItem itemName=\"SOURCE_LOCAL_MEDIA\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v60_settings` VALUES ('33', 'SOURCE_TASK_MANAGER', '任务管理', '信号源工具箱', '快捷功能', '', '0', '0', '3', '1', '信号源工具箱-选择开关 - 任务管理', '<SourceQuickItem itemName=\"SOURCE_TASK_MANAGER\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v60_settings` VALUES ('34', 'SOURCE_ACCELERATE', '一键加速', '信号源工具箱', '快捷功能', '', '0', '0', '4', '1', '信号源工具箱-选择开关 - 一键加速', '<SourceQuickItem itemName=\"SOURCE_ACCELERATE\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v60_settings` VALUES ('35', 'SOURCE_AUDIO_NLY', '单独听', '信号源工具箱', '快捷功能', '', '0', '0', '5', '1', '信号源工具箱-选择开关 - 单独听', '<SourceQuickItem itemName=\"SOURCE_AUDIO_NLY\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v60_settings` VALUES ('36', 'SOURCE_BACKLIGHT', '背光', '信号源工具箱', '常用设置', '', '0', '0', '1', '1', '信号源工具箱-选择开关 - 背光', '<SourceSettingItem itemName=\"SOURCE_BACKLIGHT\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('37', 'SOURCE_PICTURE_MODE', '图像模式', '信号源工具箱', '常用设置', '', '0', '0', '2', '1', '信号源工具箱-选择开关 - 图像模式', '<SourceSettingItem itemName=\"SOURCE_PICTURE_MODE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('38', 'SOURCE_SOUND_MODE', '声音模式', '信号源工具箱', '常用设置', '', '0', '0', '3', '1', '信号源工具箱-选择开关 - 声音模式', '<SourceSettingItem itemName=\"SOURCE_SOUND_MODE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('39', 'SOURCE_SLEEP_TIMER', '定时关机', '信号源工具箱', '常用设置', '', '0', '0', '4', '1', '信号源工具箱-选择开关 - 定时关机', '<SourceSettingItem itemName=\"SOURCE_SLEEP_TIMER\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('40', 'SOURCE_PICTURE_SOUND', '音画设置', '信号源工具箱', '常用设置', '', '0', '0', '5', '1', '信号源工具箱-选择开关 - 音画设置', '<SourceSettingItem itemName=\"SOURCE_PICTURE_SOUND\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('41', 'SOURCE_EYE_PROTECTED', '护眼模式', '信号源工具箱', '常用设置', '', '0', '0', '6', '1', '信号源工具箱-选择开关 - 护眼模式', '<SourceSettingItem itemName=\"SOURCE_EYE_PROTECTED\" /> ', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('42', 'SOURCE_INTERFACE_LIGHT_ON', '指引灯开', '信号源工具箱', '常用设置', '', '0', '0', '7', '1', '信号源工具箱-选择开关 - 指引灯开', '<SourceSettingItem itemName=\"SOURCE_INTERFACE_LIGHT_ON\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('43', 'SOURCE_NET', '网络', '信号源工具箱', '常用设置', '', '0', '0', '8', '1', '信号源工具箱-选择开关 - 网络', '<SourceSettingItem itemName=\"SOURCE_NET\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('44', 'SOURCE_SYSTEM_UPGRADE', '升级', '信号源工具箱', '常用设置', '', '0', '0', '9', '1', '信号源工具箱-选择开关 - 升级', '<SourceSettingItem itemName=\"SOURCE_SYSTEM_UPGRADE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('45', 'SOURCE_ONE_KEY_DIRECT', '一键直达', '信号源工具箱', '常用设置', '', '0', '0', '10', '1', '信号源工具箱-选择开关 - 一键直达', '<SourceSettingItem itemName=\"SOURCE_ONE_KEY_DIRECT\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('46', 'SOURCE_SPORT_MODE', '体育模式', '信号源工具箱', '常用设置', '', '0', '0', '11', '1', '信号源工具箱-选择开关 - 体育模式', '<SourceSettingItem itemName=\"SOURCE_SPORT_MODE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v60_settings` VALUES ('47', 'MARKET_SHOW_SPEAKER_SYSTEM', '魔音技术', '卖场演示', '声音演示', '', '0', '0', '2', '1', '卖场演示-选择开关 - 卖场演示中是否显示“魔音技术”演示', '<item type=\"Boolean\" key=\"SPEAKER_SYSTEM\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('48', 'MARKET_SHOW_DSP', 'DSP智能修正', '卖场演示', '声音演示', '', '0', '0', '3', '1', '卖场演示-选择开关 - 卖场演示中是否显示“DSP智能修正”演示', '<item type=\"Boolean\" key=\"DSP\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('49', 'MARKET_SHOW_VOLUME_MUTATION', '音量突变保护', '卖场演示', '声音演示', '', '0', '0', '4', '1', '卖场演示-选择开关 - 卖场演示中是否显示“音量突变保护”演示', '<item type=\"Boolean\" key=\"VOLUME_MUTATION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('50', 'MARKET_SHOW_ACCURATE_SOUND', '精准声场定位', '卖场演示', '声音演示', '', '0', '0', '5', '1', '卖场演示-选择开关 - 卖场演示中是否显示“精准声场定位”演示', '<item type=\"Boolean\" key=\"ACCURATE_SOUND\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('51', 'MARKET_SHOW_ATMOS', 'ATMOS音效', '卖场演示', '声音演示', '', '0', '0', '1', '1', '卖场演示-选择开关 - 卖场演示中是否显示“ATMOS音效”演示', '<item type=\"Boolean\" key=\"ATMOS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('52', 'MARKET_SHOW_PIXEL_CONTROL_LIGHT', '像素控光', '卖场演示', '图像演示', '', '0', '0', '1', '1', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光”演示', '<item type=\"Boolean\" key=\"PIXEL_CONTROL_LIGHT\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('53', 'MARKET_SHOW_LIMIT_CONTRAST', '像素控光-极限对比', '卖场演示', '图像演示', '', '0', '0', '2', '1', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光-极限对比”演示', '<item type=\"Boolean\" key=\"LIMIT_CONTRAST\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('54', 'MARKET_SHOW_FAST_RESPONSE', '像素控光-极速响应', '卖场演示', '图像演示', '', '0', '0', '3', '1', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光-极速响应”演示', '<item type=\"Boolean\" key=\"FAST_RESPONSE\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('55', 'MARKET_SHOW_HDR_BOOST', '像素控光-HDR Boost', '卖场演示', '图像演示', '', '0', '0', '4', '1', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光-HDR Boost”演示', '<item type=\"Boolean\" key=\"HDR_BOOST\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('56', 'MARKET_SHOW_SUPER_SHARPNESS', '超级清晰度', '卖场演示', '图像演示', '', '0', '0', '5', '1', '卖场演示-选择开关 - 卖场演示中是否显示“超级清晰度”演示', '<item type=\"Boolean\" key=\"SUPER_SHARPNESS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('57', 'MARKET_SHOW_SUPER_ONLINE_DNR', '超清在线解析', '卖场演示', '图像演示', '', '0', '0', '6', '1', '卖场演示-选择开关 - 卖场演示中是否显示“超清在线解析”演示', '<item type=\"Boolean\" key=\"SUPER_ONLINE_DNR\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('58', 'MARKET_SHOW_COLOR_STANDER_CONTROL', '精准色相控制', '卖场演示', '图像演示', '', '0', '0', '7', '1', '卖场演示-选择开关 - 卖场演示中是否显示“精准色相控制”演示', '<item type=\"Boolean\" key=\"COLOR_STANDER_CONTROL\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('59', 'MARKET_SHOW_COLOR_STANDER', '精准色控', '卖场演示', '图像演示', '', '0', '0', '8', '1', '卖场演示-选择开关 - 卖场演示中是否显示“精准色控”演示', '<item type=\"Boolean\" key=\"COLOR_STANDER\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('60', 'MARKET_SHOW_LAP', '无毒广色域', '卖场演示', '图像演示', '', '0', '0', '9', '1', '卖场演示-选择开关 - 卖场演示中是否显示“无毒广色域”演示', '<item type=\"Boolean\" key=\"LAP\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('61', 'MARKET_SHOW_SOLID_TECH', '纯色技术', '卖场演示', '图像演示', '', '0', '0', '10', '1', '卖场演示-选择开关 - 卖场演示中是否显示“纯色技术”演示', '<item type=\"Boolean\" key=\"SOLID_TECH\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('62', 'MARKET_SHOW_LAP_HIGH', 'LAP高色域', '卖场演示', '图像演示', '', '0', '0', '11', '1', '卖场演示-选择开关 - 卖场演示中是否显示“LAP高色域”演示', '<item type=\"Boolean\" key=\"LAP_HIGH\" value=\"false\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('63', 'MARKET_SHOW_MEMC', '4K MEMC+', '卖场演示', '图像演示', '', '0', '0', '12', '1', '卖场演示-选择开关 - 卖场演示中是否显示“4K MEMC+”演示', '<item type=\"Boolean\" key=\"MEMC\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('64', 'MARKET_SHOW_MICRO_DIMMING', '区域对比提升', '卖场演示', '图像演示', '', '0', '0', '13', '1', '卖场演示-选择开关 - 卖场演示中是否显示“区域对比提升”演示', '<item type=\"Boolean\" key=\"MICRO_DIMMING\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('65', 'MARKET_SHOW_LOCAL_DIMMING', 'Local Dimming', '卖场演示', '图像演示', '', '0', '0', '14', '1', '卖场演示-选择开关 - 卖场演示中是否显示“Local Dimming”演示', '<item type=\"Boolean\" key=\"LOCAL_DIMMING\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('66', 'MARKET_SHOW_HDR_10', 'HDR_10', '卖场演示', '图像演示', '', '0', '0', '15', '1', '卖场演示-选择开关 - 卖场演示中是否显示“HDR-10”演示', '<item type=\"Boolean\" key=\"HDR_10\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('67', 'MARKET_SHOW_DOBLY_VISION', 'Dobly Vision', '卖场演示', '图像演示', '', '0', '0', '16', '1', '卖场演示-选择开关 - 卖场演示中是否显示“Dobly Vision”演示', '<item type=\"Boolean\" key=\"DOBLY_VISION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('68', 'MARKET_SHOW_OPTICAL_BLUE_RAY', '光学防蓝光', '卖场演示', '图像演示', '', '0', '0', '17', '1', '卖场演示-选择开关 - 卖场演示中是否显示“光学防蓝光”演示', '<item type=\"Boolean\" key=\"OPTICAL_BLUE_RAY\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('69', 'MARKET_SHOW_LOW_REFLECTION', '低反射', '卖场演示', '图像演示', '', '0', '0', '18', '1', '卖场演示-选择开关 - 卖场演示中是否显示“低反射”演示', '<item type=\"Boolean\" key=\"LOW_REFLECTION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('70', 'MARKET_SHOW_HIGH_CONTRAST', '高对比', '卖场演示', '图像演示', '', '0', '0', '19', '1', '卖场演示-选择开关 - 卖场演示中是否显示“高对比”演示', '<item type=\"Boolean\" key=\"HIGH_CONTRAST\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('71', 'MARKET_SHOW_EYE_SAFEMODE', '护眼模式', '卖场演示', '图像演示', '', '0', '0', '20', '1', '卖场演示-选择开关 - 卖场演示中是否显示“护眼模式”演示', '<item type=\"Boolean\" key=\"EYE_SAFEMODE\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('72', 'MARKET_SHOW_PRECISE_SMOOTH', '精密平滑处理', '卖场演示', '图像演示', '', '0', '0', '21', '1', '卖场演示-选择开关 - 卖场演示中是否显示“精密平滑处理”演示', '<item type=\"Boolean\" key=\"PRECISE_SMOOTH\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('73', 'MARKET_SHOW_DYNAMIC_TARGET_REMOLDING', '动态目标重塑', '卖场演示', '图像演示', '', '0', '0', '22', '1', '卖场演示-选择开关 - 卖场演示中是否显示“动态目标重塑”演示', '<item type=\"Boolean\" key=\"DYNAMIC_TARGET_REMOLDING\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('74', 'MARKET_SHOW_DenoiseMaster', '降噪大师', '卖场演示', '图像演示', '', '0', '0', '23', '1', '卖场演示-选择开关 - 卖场演示中是否显示“降噪大师”演示', '<item type=\"Boolean\" key=\"DenoiseMaster\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('75', 'MARKET_SHOW_SquareNr', 'SquareNr', '卖场演示', '图像演示', '', '0', '0', '24', '1', '卖场演示-选择开关 - 卖场演示中是否显示“SquareNr”演示', '<item type=\"Boolean\" key=\"SquareNr\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('76', 'MARKET_SHOW_LocalDimmingBoost', '精睿控光', '卖场演示', '图像演示', '', '0', '0', '25', '1', '卖场演示-选择开关 - 卖场演示中是否显示“精睿控光”演示', '<item type=\"Boolean\" key=\"LocalDimmingBoost\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('77', 'MARKET_SHOW_FourAxisAntiShakePlus', 'MotionFlow Plus', '卖场演示', '图像演示', '', '0', '0', '26', '1', '卖场演示-选择开关 - 卖场演示中是否显示“MotionFlow Plus”演示', '<item type=\"Boolean\" key=\"FourAxisAntiShakePlus\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('78', 'MARKET_SHOW_SuperDefinitionReshape', '4K极清重塑', '卖场演示', '图像演示', '', '0', '0', '27', '1', '卖场演示-选择开关 - 卖场演示中是否显示“4K极清重塑”演示', '<item type=\"Boolean\" key=\"SuperDefinitionReshape\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('79', 'MARKET_SHOW_GAMMA_IMAGE_CALIBRATION', 'Gamma图像校准', '卖场演示', '图像演示', '', '0', '0', '28', '1', '卖场演示-选择开关 - 卖场演示中是否显示“Gamma图像校准”演示', '<item type=\"Boolean\" key=\"GAMMA_IMAGE_CALIBRATION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('80', 'MARKET_SHOW_MICRO_DIMMING_PLUS', '区域对比提升进阶版', '卖场演示', '图像演示', '', '0', '0', '29', '0', '卖场演示-选择开关 - 卖场演示中是否显示“区域对比提升进阶版”演示', '<item type=\"Boolean\" key=\"MICRO_DIMMING_PLUS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', '');
INSERT INTO `v60_settings` VALUES ('89', 'SKY_CFG_TV_BRIGHTNESS', '亮度', '系统设置', '图像设置', '基础设置', '0', '0', '1', '0', '系统设置-音画设置-图像设置-基础设置-亮度', '<SettingItem name=\"SKY_CFG_TV_BRIGHTNESS\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v60_settings` VALUES ('90', 'SKY_CFG_TV_CONTRAST', '对比度', '系统设置', '图像设置', '基础设置', '0', '0', '2', '0', '系统设置-音画设置-图像设置-基础设置-对比度', '<SettingItem name=\"SKY_CFG_TV_CONTRAST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v60_settings` VALUES ('91', 'SKY_CFG_TV_COLOR', '彩色,即饱和度', '系统设置', '图像设置', '基础设置', '0', '0', '3', '0', '系统设置-音画设置-图像设置-基础设置-彩色,即饱和度', '<SettingItem name=\"SKY_CFG_TV_COLOR\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v60_settings` VALUES ('92', 'SKY_CFG_TV_SHARPNESS', '清晰度', '系统设置', '图像设置', '基础设置', '0', '0', '4', '0', '系统设置-音画设置-图像设置-基础设置-清晰度', '<SettingItem name=\"SKY_CFG_TV_SHARPNESS\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v60_settings` VALUES ('93', 'SKY_CFG_TV_MANUAL_BACKLIGHT_ADJUST', '背光调节', '系统设置', '图像设置', '基础设置', '0', '0', '5', '0', '系统设置-音画设置-图像设置-基础设置-背光调节', '<SettingItem name=\"SKY_CFG_TV_MANUAL_BACKLIGHT_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v60_settings` VALUES ('94', 'SKY_CFG_TV_NEW_EYE_PROTECT_SWITCH', '护眼模式开关', '系统设置', '图像设置', '基础设置', '0', '0', '6', '0', '系统设置-音画设置-图像设置-基础设置-护眼模式开关', '<SettingItem name=\"SKY_CFG_TV_NEW_EYE_PROTECT_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v60_settings` VALUES ('95', 'SKY_CFG_TV_LOCAL_DIMMING_MODE', '矩阵背光,需要和屏变关联', '系统设置', '图像设置', '高级亮度设置', '0', '0', '1', '0', '系统设置-音画设置-图像设置-高级亮度设置-矩阵背光,需要和屏变关联', '<SettingItem name=\"SKY_CFG_TV_LOCAL_DIMMING_MODE\" association=\"SKY_CFG_TV_DREAM_PANEL\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('96', 'SKY_CFG_CC_DYNAMIC_CONTRAST', '动态对比度', '系统设置', '图像设置', '高级亮度设置', '0', '0', '2', '0', '系统设置-音画设置-图像设置-高级亮度设置-动态对比度', '<SettingItem name=\"SKY_CFG_CC_DYNAMIC_CONTRAST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('97', 'SKY_CFG_CC_BLACK_STRETCH', '黑色增强', '系统设置', '图像设置', '高级亮度设置', '0', '0', '3', '0', '系统设置-音画设置-图像设置-高级亮度设置-黑色增强', '<SettingItem name=\"SKY_CFG_CC_BLACK_STRETCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('98', 'SKY_CFG_TV_SDR_TO_HDR_SWITCH', 'SDR转HDR', '系统设置', '图像设置', '高级亮度设置', '0', '0', '4', '0', '系统设置-音画设置-图像设置-高级亮度设置-SDR 转 HDR：动态对比度关闭需要灰掉此项', '<SettingItem name=\"SKY_CFG_TV_SDR_TO_HDR_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('99', 'SKY_CFG_TV_LOCAL_CONTRAST_SWITCH', '区域对比提升', '系统设置', '图像设置', '高级亮度设置', '0', '0', '5', '0', '系统设置-音画设置-图像设置-高级亮度设置-区域对比提升', '<SettingItem name=\"SKY_CFG_TV_LOCAL_CONTRAST_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('100', 'SKY_CFG_TV_DREAM_PANEL', '屏变', '系统设置', '图像设置', '高级亮度设置', '0', '0', '6', '0', '系统设置-音画设置-图像设置-高级亮度设置-屏变，需要和矩阵背光关联', '<SettingItem name=\"SKY_CFG_TV_DREAM_PANEL\" association=\"SKY_CFG_TV_LOCAL_DIMMING_MODE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('101', 'SKY_CFG_BACKLIGHT_BOOST', '峰值亮度扩展', '系统设置', '图像设置', '高级亮度设置', '0', '0', '7', '0', '系统设置-音画设置-图像设置-高级亮度设置-峰值亮度扩展 ：OLED无此项', '<SettingItem name=\"SKY_CFG_BACKLIGHT_BOOST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('102', 'SKY_CFG_SPECULAR_BOOST', '动态范围扩展', '系统设置', '图像设置', '高级亮度设置', '0', '0', '8', '0', '系统设置-音画设置-图像设置-高级亮度设置-动态范围扩展', '<SettingItem name=\"SKY_CFG_SPECULAR_BOOST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v60_settings` VALUES ('103', 'SKY_CFG_TV_COLOR_TEMPERATURE', '色温', '系统设置', '图像设置', '彩色设置', '0', '0', '1', '0', '系统设置-音画设置-图像设置-彩色设置-色温', '<SettingItem name=\"SKY_CFG_TV_COLOR_TEMPERATURE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v60_settings` VALUES ('104', 'SKY_CFG_CC_GAIN_RED', '红色增益', '系统设置', '图像设置', '彩色设置', '0', '0', '2', '0', '系统设置-音画设置-图像设置-彩色设置-红色增益', '<SettingItem name=\"SKY_CFG_CC_GAIN_RED\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v60_settings` VALUES ('105', 'SKY_CFG_CC_GAIN_GREEN', '绿色增益', '系统设置', '图像设置', '彩色设置', '0', '0', '3', '0', '系统设置-音画设置-图像设置-彩色设置-绿色增益', '<SettingItem name=\"SKY_CFG_CC_GAIN_GREEN\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v60_settings` VALUES ('106', 'SKY_CFG_CC_GAIN_BLUE', '蓝色增益', '系统设置', '图像设置', '彩色设置', '0', '0', '4', '0', '系统设置-音画设置-图像设置-彩色设置-蓝色增益', '<SettingItem name=\"SKY_CFG_CC_GAIN_BLUE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v60_settings` VALUES ('107', 'SKY_CFG_FLESH_TONE', '肤色偏好', '系统设置', '图像设置', '彩色设置', '0', '0', '5', '0', '系统设置-音画设置-图像设置-彩色设置-肤色偏好', '<SettingItem name=\"SKY_CFG_FLESH_TONE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v60_settings` VALUES ('108', 'SKY_CFG_CC_BLUE_STRETCH', '蓝电平延伸', '系统设置', '图像设置', '彩色设置', '0', '0', '6', '0', '系统设置-音画设置-图像设置-彩色设置-蓝电平延伸', '<SettingItem name=\"SKY_CFG_CC_BLUE_STRETCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v60_settings` VALUES ('109', 'SKY_CFG_CC_SUPER_RESOLUTION', '超解像', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '1', '0', '系统设置-音画设置-图像设置-高级清晰度设置-默认超解像,可改名为：超级4K增补，超级清晰度等', '<SettingItem name=\"SKY_CFG_CC_SUPER_RESOLUTION\" ></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v60_settings` VALUES ('110', 'SKY_CFG_AI_DEJAGGY', 'AI抗锯齿', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '2', '0', '系统设置-音画设置-图像设置-高级清晰度设置-AI抗锯齿', '<SettingItem name=\"SKY_CFG_AI_DEJAGGY\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v60_settings` VALUES ('111', 'SKY_CFG_TV_DNR', '降噪', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '3', '0', '系统设置-音画设置-图像设置-高级清晰度设置-默认降噪，可改名为：动态目标重塑', '<SettingItem name=\"SKY_CFG_TV_DNR\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v60_settings` VALUES ('112', 'SKY_CFG_CC_DE_CONTOUR', '平滑处理', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '4', '0', '系统设置-音画设置-图像设置-高级清晰度设置-默认平滑处理，可改名为：精密平滑处理', '<SettingItem name=\"SKY_CFG_CC_DE_CONTOUR\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v60_settings` VALUES ('113', 'SKY_CFG_CC_DE_BLOCK', '块噪声消除', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '5', '0', '系统设置-音画设置-图像设置-高级清晰度设置-块噪声消除，蚊状噪声消除 两个合并为一个：MPEG降噪', '<SettingItem name=\"SKY_CFG_CC_DE_BLOCK\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v60_settings` VALUES ('114', 'SKY_CFG_CC_MEMC', '动态图像校正MEMC', '系统设置', '图像设置', '运动设置', '0', '0', '1', '0', '系统设置-音画设置-图像设置-运动设置-动态图像校正MEMC', '<SettingItem name=\"SKY_CFG_CC_MEMC\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_MOTION_SETTING');
INSERT INTO `v60_settings` VALUES ('115', 'SKY_CFG_TV_NEW_EQUALIZER', '新版均衡器', '系统设置', '声音设置', '基础设置', '0', '0', '1', '0', '系统设置-音画设置-声音设置-基础设置-新版均衡器', '<SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER\" type=\"TYPE_CONTAINER\" transparent=\"true\"><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_BASS\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_MIDBASS\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_ALTO\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_ALT\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_TREBLE\"></SettingItem></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v60_settings` VALUES ('116', 'SKY_CFG_TV_SURROUND', '环绕声、Atoms音效、DTS音效', '系统设置', '声音设置', '基础设置', '0', '0', '2', '0', '系统设置-音画设置-声音设置-基础设置-环绕声、Atoms音效、DTS音效', '<SettingItem name=\"SKY_CFG_TV_SURROUND\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v60_settings` VALUES ('117', 'SKY_CFG_TV_INTEL_CONTROL_VOLUME', '智能音量控制', '系统设置', '声音设置', '基础设置', '0', '0', '3', '0', '系统设置-音画设置-声音设置-基础设置-智能音量控制', '<SettingItem name=\"SKY_CFG_TV_INTEL_CONTROL_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v60_settings` VALUES ('118', 'SKY_CFG_TV_SUBWOOFER_VOLUME', '重低音音量', '系统设置', '声音设置', '基础设置', '0', '0', '4', '0', '系统设置-音画设置-声音设置-基础设置-重低音音量', '<SettingItem name=\"SKY_CFG_TV_SUBWOOFER_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v60_settings` VALUES ('119', 'SKY_CFG_TV_AUDIO_OUTPUT', '声音输出', '系统设置', '声音设置', '声音输出设置', '0', '0', '1', '0', '系统设置-音画设置-声音设置-声音输出设置-声音输出', '<SettingItem name=\"SKY_CFG_TV_AUDIO_OUTPUT\" association=\"SKY_CFG_TV_SOUND_SPDIF\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v60_settings` VALUES ('120', 'SKY_CFG_TV_SOUND_SPDIF', 'SPDIF输出', '系统设置', '声音设置', '声音输出设置', '0', '0', '2', '0', '系统设置-音画设置-声音设置-声音输出设置-SPDIF输出,后改名为：数字音频输出', '<SettingItem name=\"SKY_CFG_TV_SOUND_SPDIF\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v60_settings` VALUES ('121', 'SKY_CFG_TV_BOOT_VIDEO_SOUND_SWITCH', '开机音频输出', '系统设置', '声音设置', '声音输出设置', '0', '0', '3', '0', '系统设置-音画设置-声音设置-声音输出设置-开机音频输出，开始定放通用设置，后来决定放到这里', '<SettingItem name=\"SKY_CFG_TV_BOOT_VIDEO_SOUND_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v60_settings` VALUES ('122', 'SKY_CFG_TV_INSTALL_MODE', '声音场景', '系统设置', '声音设置', '声音输出设置', '0', '0', '4', '0', '系统设置-音画设置-声音设置-电视安装方式,后改名为：声音场景（W8等机器有此项）', '<SettingItem name=\"SKY_CFG_TV_INSTALL_MODE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v60_settings` VALUES ('123', 'SKY_CFG_TV_ATMOS_SOUND_EFFECTS', 'ATMOS音效', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '1', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-ATMOS音效', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SOUND_EFFECTS\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('124', 'SKY_CFG_TV_ATMOS_DRC', '动态范围控制', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '2', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-动态范围控制', '<SettingItem name=\"SKY_CFG_TV_ATMOS_DRC\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('125', 'SKY_CFG_TV_ATMOS_SUBWOOFER_VOLUME', '重低音微调', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '3', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-重低音微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SUBWOOFER_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('126', 'SKY_CFG_TV_ATMOS_SCENE_SELECT', '场景选择', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '4', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-场景选择', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SCENE_SELECT\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('127', 'SKY_CFG_TV_ATMOS_MAIN_SOUNDTRACK_VOLUME', '主声道微调', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '5', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-主声道微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_MAIN_SOUNDTRACK_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('128', 'SKY_CFG_TV_ATMOS_MIDDLE_VOLUME', '中置音量微调', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '6', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-中置音量微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_MIDDLE_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('129', 'SKY_CFG_TV_ATMOS_SURROUND_LEFT_VOLUME_ADJUST', '左环绕声微调', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '7', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-左环绕声微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SURROUND_LEFT_VOLUME_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('130', 'SKY_CFG_TV_ATMOS_SURROUND_RIGHT_VOLUME_ADJUST', '右环绕声微调', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '8', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-右环绕声微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SURROUND_RIGHT_VOLUME_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('131', 'SKY_CFG_TV_ATMOS_PANORAMIC_VOLUME_ADJUST', '全景音量微调', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '9', '0', '系统设置-音画设置-声音设置-ATMOS专业音效设置-全景音量微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_PANORAMIC_VOLUME_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v60_settings` VALUES ('132', 'MIDWARE_ATVRF', 'ATVRF', '中间件', '输入信号源', '', '0', '0', '6', '0', '系统设置-中间件-输入信号源-ATVRF', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('133', 'MIDWARE_DVBC', 'DVBC', '中间件', '输入信号源', '', '0', '0', '7', '0', '系统设置-中间件-输入信号源-DVBC', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('134', 'MIDWARE_DTMB', 'DTMB', '中间件', '输入信号源', '', '0', '0', '8', '0', '系统设置-中间件-输入信号源-DTMB', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('135', 'MIDWARE_CVBS1', 'CVBS1', '中间件', '输入信号源', '', '0', '0', '9', '0', '系统设置-中间件-输入信号源-CVBS1', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('136', 'MIDWARE_CVBS2', 'CVBS2', '中间件', '输入信号源', '', '0', '0', '10', '0', '系统设置-中间件-输入信号源-CVBS2', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('137', 'MIDWARE_CVBS3', 'CVBS3', '中间件', '输入信号源', '', '0', '0', '11', '0', '系统设置-中间件-输入信号源-CVBS3', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('138', 'MIDWARE_VGA', 'VGA', '中间件', '输入信号源', '', '0', '0', '12', '0', '系统设置-中间件-输入信号源-VGA', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('139', 'MIDWARE_YPBPR1', 'YPBPR1', '中间件', '输入信号源', '', '0', '0', '13', '0', '系统设置-中间件-输入信号源-YPBPR1', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('140', 'MIDWARE_YPBPR2', 'YPBPR2', '中间件', '输入信号源', '', '0', '0', '14', '0', '系统设置-中间件-输入信号源-YPBPR2', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('141', 'MIDWARE_HDMI1', 'HDMI1', '中间件', '输入信号源', '', '0', '0', '1', '0', '系统设置-中间件-输入信号源-HDMI1', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('142', 'MIDWARE_HDMI2', 'HDMI2', '中间件', '输入信号源', '', '0', '0', '2', '0', '系统设置-中间件-输入信号源-HDMI2', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('143', 'MIDWARE_HDMI3', 'HDMI3', '中间件', '输入信号源', '', '0', '0', '3', '0', '系统设置-中间件-输入信号源-HDMI3', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('144', 'MIDWARE_HDMI4', 'HDMI4', '中间件', '输入信号源', '', '0', '0', '4', '0', '系统设置-中间件-输入信号源-HDMI4', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('145', 'MIDWARE_MEDIA', 'MEDIA', '中间件', '输入信号源', '', '0', '0', '5', '0', '系统设置-中间件-输入信号源-MEDIA', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('146', 'MIDWARE_16To9', '16To9', '中间件', '支持纵横比', '', '0', '0', '1', '0', '系统设置-中间件-支持纵横比-16To9', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('147', 'MIDWARE_4To3', '4To3', '中间件', '支持纵横比', '', '0', '0', '2', '0', '系统设置-中间件-支持纵横比-4To3', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('148', 'MIDWARE_Full', 'Full', '中间件', '支持纵横比', '', '0', '0', '3', '0', '系统设置-中间件-支持纵横比-Full', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('149', 'MIDWARE_PToP', 'PToP', '中间件', '支持纵横比', '', '0', '0', '4', '0', '系统设置-中间件-支持纵横比-PToP', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('150', 'MIDWARE_Auto', 'Auto', '中间件', '支持纵横比', '', '0', '0', '5', '0', '系统设置-中间件-支持纵横比-Auto', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('151', 'MIDWARE_Zoom', 'Zoom', '中间件', '支持纵横比', '', '0', '0', '6', '0', '系统设置-中间件-支持纵横比-Zoom', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('152', 'MIDWARE_Subtitle', 'Subtitle', '中间件', '支持纵横比', '', '0', '0', '7', '0', '系统设置-中间件-支持纵横比-Subtitle', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('153', 'MIDWARE_Cinema', 'Cinema', '中间件', '支持纵横比', '', '0', '0', '8', '0', '系统设置-中间件-支持纵横比-Cinema', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
INSERT INTO `v60_settings` VALUES ('154', 'MIDWARE_Panorama', 'Panorama', '中间件', '支持纵横比', '', '0', '0', '9', '0', '系统设置-中间件-支持纵横比-Panorama', '<!-- 未知XML行  -->', 'driverbase_net_config.ini', 'type1', 'type2');
