/*
Navicat MySQL Data Transfer

Source Server         : 172.20.5.239
Source Server Version : 50560
Source Host           : 172.20.5.239:3306
Source Database       : scm

Target Server Type    : MYSQL
Target Server Version : 50560
File Encoding         : 65001

Date: 2018-07-09 20:32:23
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `v62_settings`
-- ----------------------------
DROP TABLE IF EXISTS `v62_settings`;
CREATE TABLE `v62_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `engName` char(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cnName` char(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `defaultSelected` int(11) DEFAULT '0',
  `level1` char(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level2` char(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `level3` char(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `level2_order` int(11) NOT NULL,
  `level3_order` int(11) NOT NULL,
  `orderId` int(11) NOT NULL,
  `descText` mediumtext COLLATE utf8mb4_unicode_ci,
  `xmlText` varchar(4095) COLLATE utf8mb4_unicode_ci NOT NULL,
  `xmlFileName` char(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `xmlNode1` char(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `xmlNode2` char(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `engName_index` (`engName`(64))
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of v62_settings
-- ----------------------------
INSERT INTO `v62_settings` VALUES (null, 'net_connect_setting', '网络与连接', '1', '系统设置', '设置入口页', '', '0', '0', '1', '系统设置主大块 - 网络与连接', '<SettingModual modualName=\"net_connect_setting\" modualIcon=\"main_setting_connect\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.ConnectSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'picture_sound_setting', '图像与声音', '1', '系统设置', '设置入口页', '', '0', '0', '2', '系统设置主大块 - 图像与声音', '<SettingModual modualName=\"picture_sound_setting\" modualIcon=\"main_setting_picturesound\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.PictureSoundSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'general_setting', '通用设置', '1', '系统设置', '设置入口页', '', '0', '0', '3', '系统设置主大块 - 通用设置', '<SettingModual modualName=\"general_setting\" modualIcon=\"main_setting_general\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.GeneralSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'account_payment_setting', '账户与支付', '1', '系统设置', '设置入口页', '', '0', '0', '4', '系统设置主大块 - 账户与支付', '<SettingModual modualName=\"account_payment_setting\" modualIcon=\"main_setting_accountpayment\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.AccountPaymentSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'system_upgrade_setting', '升级', '1', '系统设置', '设置入口页', '', '0', '0', '5', '系统设置主大块 - 升级', '<SettingModual modualName=\"system_upgrade_setting\" modualIcon=\"main_setting_upgrade\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.SystemUpgradeSetting\" />', 'setting_main.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'about_tv_setting', '关于本机', '1', '系统设置', '设置入口页', '', '0', '0', '6', '系统设置主大块 - 关于本机', '<SettingModual modualName=\"about_tv_setting\" modualIcon=\"main_setting_about_tv\" modualAction=\"ACTION_ENTER_ACTIVITY\" modualParams=\"com.tianci.setting.activity.AboutTvSetting\"/>', 'setting_main.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SettingGuide_pageName_NET', '网络连接', '1', '系统设置', '开机引导', '', '0', '0', '1', '开机引导的选择开关 - 网络连接页', '<SettingGuide pageName=\"NET\" className = \"com.tianci.setting.guidesetting.SkyGuideNetActivity\" stepText=\"guide_connect\" isCanSkipNet=\"false\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SettingGuide_pageName_AWARD', '激活电视', '1', '系统设置', '开机引导', '', '0', '0', '2', '开机引导的选择开关 - 激活电视页', '<SettingGuide pageName=\"AWARD\" className = \"com.tianci.setting.guidesetting.SkyGuideAward\" stepText=\"guide_active\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SettingGuide_pageName_ACCOUNT', '默认配置', '1', '系统设置', '开机引导', '', '0', '0', '3', '开机引导的选择开关 - 默认配置页，不用管', '<SettingGuide pageName=\"ACCOUNT\" className = \"com.tianci.setting.guidesetting.SkyGuideAccount\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SettingGuide_pageName_QR', '酷开会员', '1', '系统设置', '开机引导', '', '0', '0', '4', '开机引导的选择开关 - 酷开会员页', '<SettingGuide pageName=\"QR\" className = \"com.tianci.setting.guidesetting.SkyGuideQRActivity\" stepText=\"guide_coocaa_member\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SettingGuide_pageName_BT', '蓝牙配对(不支持语音键)', '0', '系统设置', '开机引导', '', '0', '0', '5', '开机引导的选择开关 - 标配蓝牙遥控器配对', '<SettingGuide pageName=\"BT\" className = \"com.tianci.setting.connectsetting.btonekey.OneKeyActivity\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SettingGuide_pageName_BT_VKEY', '蓝牙配对(支持语音键一键配对)', '0', '系统设置', '开机引导', '', '0', '0', '6', '开机引导的选择开关 - 标配蓝牙遥控器配对(支持语音键一键配对)', '<SettingGuide pageName=\"BT\" className = \"com.tianci.setting.connectsetting.btonekey.OneKeyActivity\" isSupportVoiceKeyPair=\"true\" />', 'setting_guide.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_NET_WIFI', '无线网络', '1', '系统设置', '网络与连接', '', '0', '0', '1', '系统设置-网络与连接XML配置 - 无线网络', '<SettingModual modualName=\"SKY_CFG_TV_NET_WIFI\" type=\"TYPE_WIFI\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_NET_ETHERNET', '有线网络', '1', '系统设置', '网络与连接', '', '0', '0', '2', '系统设置-网络与连接XML配置 - 有线网络', '<SettingModual modualName=\"SKY_CFG_TV_NET_ETHERNET\" type=\"TYPE_ETHERNET\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_NET_WIFI_HOTSPOT', '热点', '1', '系统设置', '网络与连接', '', '0', '0', '3', '系统设置-网络与连接XML配置 - 热点', '<SettingModual modualName=\"SKY_CFG_TV_NET_WIFI_HOTSPOT\" type=\"TYPE_WIFI_HOSTSPOT\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_BLUETOOTH', '内置蓝牙dongle', '0', '系统设置', '网络与连接', '', '0', '0', '4', '系统设置-网络与连接XML配置 - 内置蓝牙dongle', '<SettingModual modualName=\"SKY_CFG_TV_BLUETOOTH\" type=\"TYPE_BLUETOOTH\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_BLUETOOTH_useDongle', '外置蓝牙dongle', '0', '系统设置', '网络与连接', '', '0', '0', '5', '系统设置-网络与连接XML配置 - 外置蓝牙dongle', '<SettingModual modualName=\"SKY_CFG_TV_BLUETOOTH\" type=\"TYPE_BLUETOOTH\" params=\"useDongle\"/>', 'setting_connect.xml', 'Setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_SYSTEM_ENV_SLEEP_TIMER', '睡眠时间', '1', '系统设置', '通用设置', '个性化设置', '0', '0', '1', '系统设置-通用- - 睡眠时间：即定时关机', '<SettingItem name=\"SKY_SYSTEM_ENV_SLEEP_TIMER\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_SYSTEM_ENV_START_SCREEN_SAVER_MODE', '屏保时间', '1', '系统设置', '通用设置', '个性化设置', '0', '0', '2', '系统设置-通用- - 屏保时间，有屏保的默认配置，OLED不配置此项，OLED默认2分钟执行屏保', '<SettingItem name=\"SKY_SYSTEM_ENV_START_SCREEN_SAVER_MODE\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_TVNAME', '本机名称', '1', '系统设置', '通用设置', '个性化设置', '0', '0', '3', '系统设置-通用- - 本机名称', '<SettingItem name=\"SKY_CFG_TV_TVNAME\" description=\"SKY_CFG_TV_TVNAME_DESCRIPTION\" from=\"Setting\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.PersonallySetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_AI_CLOSE_SCREEN_SWITCH', 'AI待机', '0', '系统设置', '通用设置', '个性化设置', '0', '0', '4', '系统设置-通用- - AI待机', '<SettingItem name=\"SKY_CFG_TV_AI_CLOSE_SCREEN_SWITCH\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_PERSONALIZE_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_LANGUAGE', '语言设置', '1', '系统设置', '通用设置', '系统设置', '0', '0', '1', '系统设置-通用- - 语言设置，通用', '<SettingItem name=\"SKY_CFG_TV_LANGUAGE\" from=\"Setting\" type=\"TYPE_INFO\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.GeneralSystemSetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SWITCH_INPUT_METHOD', '输入法', '1', '系统设置', '通用设置', '系统设置', '0', '0', '2', '系统设置-通用- - 输入法，通用', '<SettingItem name=\"SKY_CFG_TV_SWITCH_INPUT_METHOD\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_SYSTEM_ENV_BOOT_START_HOME_PAGE', '开机启动主页', '1', '系统设置', '通用设置', '系统设置', '0', '0', '3', '系统设置-通用- - 开机启动主页，所有产品', '<SettingItem name=\"SKY_SYSTEM_ENV_BOOT_START_HOME_PAGE\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_BOOT_SOURCE', '开机通道', '1', '系统设置', '通用设置', '系统设置', '0', '0', '4', '系统设置-通用- - 开机通道', '<SettingItem name=\"SKY_CFG_TV_BOOT_SOURCE\" from=\"TV\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ONE_KEY_ACTION', '一键直达', '0', '系统设置', '通用设置', '系统设置', '0', '0', '5', '系统设置-通用- - 一键直达', '<SettingItem name=\"SKY_CFG_TV_ONE_KEY_ACTION\" description=\"SKY_CFG_TV_ONE_KEY_ACTION_DESCRIPTION\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.PersonallySetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_SYSTEM_ENV_INTERACTION_SWITCH', '互动开关', '0', '系统设置', '通用设置', '系统设置', '0', '0', '6', '系统设置-通用- - 互动开关，酷云勾正之类的可配置', '<SettingItem name=\"SKY_SYSTEM_ENV_INTERACTION_SWITCH\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SET_TOUCH_CONTROL_SWITCH', '触控开关', '0', '系统设置', '通用设置', '系统设置', '0', '0', '7', '系统设置-通用- - 触控开关', '<SettingItem name=\"SKY_CFG_TV_SET_TOUCH_CONTROL_SWITCH\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_EDID', 'EDID开关', '1', '系统设置', '通用设置', '系统设置', '0', '0', '8', '系统设置-通用- - EDID开关', '<SettingItem name=\"SKY_CFG_TV_EDID\" from=\"Setting\" type=\"TYPE_INFO\" description=\"SKY_CFG_TV_EDID_DESCRIPTION\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.GeneralSystemSetting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_INDICATOR_LIGHT_AUTO_OFF_SWITCH', '指示灯勿扰开关', '0', '系统设置', '通用设置', '系统设置', '0', '0', '9', '系统设置-通用- - 指示灯勿扰开关', '<SettingItem name=\"SKY_CFG_TV_INDICATOR_LIGHT_AUTO_OFF_SWITCH\" description=\"SKY_CFG_TV_INDICATOR_LIGHT_AUTO_OFF_SWITCH_DESCRIPTION\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_CLOSE_SCREEN_SOUND_SWITCH', '关屏待机', '0', '系统设置', '通用设置', '系统设置', '0', '0', '10', '系统设置-通用- - 关屏待机', '<SettingItem name=\"SKY_CFG_TV_CLOSE_SCREEN_SOUND_SWITCH\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_SYSTEM_SETTING', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_INSTALL_UNKNOWN_SOURCE_APP', '未知来源', '1', '系统设置', '通用设置', '位置与安全', '0', '0', '1', '系统设置-通用- - 未知来源', '<SettingItem name=\"SKY_CFG_TV_INSTALL_UNKNOWN_SOURCE_APP\" description=\"SKY_CFG_TV_INSTALL_UNKNOWN_SOURCE_APP_DESCRIPTION\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_LOCATION_SECURITY', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SET_INSTALL_LOCATION', '应用默认安装位置', '0', '系统设置', '通用设置', '位置与安全', '0', '0', '2', '应用默认安装位置,有SD卡需要配置此项', '<SettingItem name=\"SKY_CFG_TV_SET_INSTALL_LOCATION\" description=\"SKY_CFG_TV_SET_INSTALL_LOCATION_DESCRIPTION\" from=\"Setting\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_LOCATION_SECURITY', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_RECOVERY', '恢复出厂设置', '1', '系统设置', '通用设置', '位置与安全', '0', '0', '3', '系统设置-通用- - 恢复出厂设置', '<SettingItem name=\"SKY_CFG_TV_RECOVERY\" type=\"TYPE_DIALOG\" description=\"SKY_CFG_TV_RECOVERY_DESCRIPTION\"></SettingItem>', 'setting_general.xml', 'SKY_CFG_TV_LOCATION_SECURITY', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_MY_APPS', '我的应用', '1', '信号源工具箱', '快捷功能', '', '0', '0', '1', '信号源工具箱-选择开关 - 我的应用', '<SourceQuickItem itemName=\"SOURCE_MY_APPS\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_LOCAL_MEDIA', '本地媒体', '1', '信号源工具箱', '快捷功能', '', '0', '0', '2', '信号源工具箱-选择开关 - 本地媒体', '<SourceQuickItem itemName=\"SOURCE_LOCAL_MEDIA\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_TASK_MANAGER', '任务管理', '1', '信号源工具箱', '快捷功能', '', '0', '0', '3', '信号源工具箱-选择开关 - 任务管理', '<SourceQuickItem itemName=\"SOURCE_TASK_MANAGER\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_ACCELERATE', '一键加速', '1', '信号源工具箱', '快捷功能', '', '0', '0', '4', '信号源工具箱-选择开关 - 一键加速', '<SourceQuickItem itemName=\"SOURCE_ACCELERATE\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_AUDIO_NLY', '单独听', '1', '信号源工具箱', '快捷功能', '', '0', '0', '5', '信号源工具箱-选择开关 - 单独听', '<SourceQuickItem itemName=\"SOURCE_AUDIO_NLY\" />', 'ssc_item.xml', 'source_quick_entry', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_BACKLIGHT', '背光', '1', '信号源工具箱', '常用设置', '', '0', '0', '1', '信号源工具箱-选择开关 - 背光', '<SourceSettingItem itemName=\"SOURCE_BACKLIGHT\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_PICTURE_MODE', '图像模式', '1', '信号源工具箱', '常用设置', '', '0', '0', '2', '信号源工具箱-选择开关 - 图像模式', '<SourceSettingItem itemName=\"SOURCE_PICTURE_MODE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_SOUND_MODE', '声音模式', '1', '信号源工具箱', '常用设置', '', '0', '0', '3', '信号源工具箱-选择开关 - 声音模式', '<SourceSettingItem itemName=\"SOURCE_SOUND_MODE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_SLEEP_TIMER', '定时关机', '1', '信号源工具箱', '常用设置', '', '0', '0', '4', '信号源工具箱-选择开关 - 定时关机', '<SourceSettingItem itemName=\"SOURCE_SLEEP_TIMER\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_PICTURE_SOUND', '音画设置', '1', '信号源工具箱', '常用设置', '', '0', '0', '5', '信号源工具箱-选择开关 - 音画设置', '<SourceSettingItem itemName=\"SOURCE_PICTURE_SOUND\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_EYE_PROTECTED', '护眼模式', '0', '信号源工具箱', '常用设置', '', '0', '0', '6', '信号源工具箱-选择开关 - 护眼模式', '<SourceSettingItem itemName=\"SOURCE_EYE_PROTECTED\" /> ', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_INTERFACE_LIGHT_ON', '指引灯开', '0', '信号源工具箱', '常用设置', '', '0', '0', '7', '信号源工具箱-选择开关 - 指引灯开', '<SourceSettingItem itemName=\"SOURCE_INTERFACE_LIGHT_ON\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_NET', '网络', '1', '信号源工具箱', '常用设置', '', '0', '0', '8', '信号源工具箱-选择开关 - 网络', '<SourceSettingItem itemName=\"SOURCE_NET\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_SYSTEM_UPGRADE', '升级', '1', '信号源工具箱', '常用设置', '', '0', '0', '9', '信号源工具箱-选择开关 - 升级', '<SourceSettingItem itemName=\"SOURCE_SYSTEM_UPGRADE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_ONE_KEY_DIRECT', '一键直达', '0', '信号源工具箱', '常用设置', '', '0', '0', '10', '信号源工具箱-选择开关 - 一键直达', '<SourceSettingItem itemName=\"SOURCE_ONE_KEY_DIRECT\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SOURCE_SPORT_MODE', '体育模式', '1', '信号源工具箱', '常用设置', '', '0', '0', '11', '信号源工具箱-选择开关 - 体育模式', '<SourceSettingItem itemName=\"SOURCE_SPORT_MODE\" />', 'ssc_item.xml', 'source_setting', '');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_BRIGHTNESS', '亮度', '1', '系统设置', '图像设置', '基础设置', '0', '0', '1', '系统设置-音画设置-图像设置-基础设置-亮度', '<SettingItem name=\"SKY_CFG_TV_BRIGHTNESS\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_CONTRAST', '对比度', '1', '系统设置', '图像设置', '基础设置', '0', '0', '2', '系统设置-音画设置-图像设置-基础设置-对比度', '<SettingItem name=\"SKY_CFG_TV_CONTRAST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_COLOR', '彩色,即饱和度', '1', '系统设置', '图像设置', '基础设置', '0', '0', '3', '系统设置-音画设置-图像设置-基础设置-彩色,即饱和度', '<SettingItem name=\"SKY_CFG_TV_COLOR\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SHARPNESS', '清晰度', '1', '系统设置', '图像设置', '基础设置', '0', '0', '4', '系统设置-音画设置-图像设置-基础设置-清晰度', '<SettingItem name=\"SKY_CFG_TV_SHARPNESS\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_MANUAL_BACKLIGHT_ADJUST', '背光调节', '1', '系统设置', '图像设置', '基础设置', '0', '0', '5', '系统设置-音画设置-图像设置-基础设置-背光调节', '<SettingItem name=\"SKY_CFG_TV_MANUAL_BACKLIGHT_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_NEW_EYE_PROTECT_SWITCH', '护眼模式开关', '0', '系统设置', '图像设置', '基础设置', '0', '0', '6', '系统设置-音画设置-图像设置-基础设置-护眼模式开关', '<SettingItem name=\"SKY_CFG_TV_NEW_EYE_PROTECT_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_MOVE_ZOOM', '显示区域（盒子专用）', '0', '系统设置', '图像设置', '基础设置', '0', '0', '7', '系统设置-音画设置-图像设置-基础设置-显示区域（盒子专用）', '<SettingItem name=\"SKY_CFG_TV_MOVE_ZOOM\" from=\"Setting\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.PersonallySetting\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_RESOLUTION', '分辨率（盒子专用）', '0', '系统设置', '图像设置', '基础设置', '0', '0', '8', '系统设置-音画设置-图像设置-基础设置-分辨率（盒子专用）', '<SettingItem name=\"SKY_CFG_TV_RESOLUTION\" from=\"Setting\" type=\"TYPE_INFO\" pkgname=\"com.tianci.setting\" clsname=\"com.tianci.setting.generalsetting.GeneralSystemSetting\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_ADJUST');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_LOCAL_DIMMING_MODE', '矩阵背光,需要和屏变关联', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '1', '系统设置-音画设置-图像设置-高级亮度设置-矩阵背光,需要和屏变关联', '<SettingItem name=\"SKY_CFG_TV_LOCAL_DIMMING_MODE\" association=\"SKY_CFG_TV_DREAM_PANEL\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_DYNAMIC_CONTRAST', '动态对比度', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '2', '系统设置-音画设置-图像设置-高级亮度设置-动态对比度', '<SettingItem name=\"SKY_CFG_CC_DYNAMIC_CONTRAST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_BLACK_STRETCH', '黑色增强', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '3', '系统设置-音画设置-图像设置-高级亮度设置-黑色增强', '<SettingItem name=\"SKY_CFG_CC_BLACK_STRETCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SDR_TO_HDR_SWITCH', 'SDR转HDR', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '4', '系统设置-音画设置-图像设置-高级亮度设置-SDR 转 HDR：动态对比度关闭需要灰掉此项', '<SettingItem name=\"SKY_CFG_TV_SDR_TO_HDR_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_LOCAL_CONTRAST_SWITCH', '区域对比提升', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '5', '系统设置-音画设置-图像设置-高级亮度设置-区域对比提升', '<SettingItem name=\"SKY_CFG_TV_LOCAL_CONTRAST_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_DREAM_PANEL', '屏变', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '6', '系统设置-音画设置-图像设置-高级亮度设置-屏变，需要和矩阵背光关联', '<SettingItem name=\"SKY_CFG_TV_DREAM_PANEL\" association=\"SKY_CFG_TV_LOCAL_DIMMING_MODE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_BACKLIGHT_BOOST', '峰值亮度扩展', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '7', '系统设置-音画设置-图像设置-高级亮度设置-峰值亮度扩展 ：OLED无此项', '<SettingItem name=\"SKY_CFG_BACKLIGHT_BOOST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_SPECULAR_BOOST', '动态范围扩展', '0', '系统设置', '图像设置', '高级亮度设置', '0', '0', '8', '系统设置-音画设置-图像设置-高级亮度设置-动态范围扩展', '<SettingItem name=\"SKY_CFG_SPECULAR_BOOST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_BRIGHT_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_COLOR_TEMPERATURE', '色温', '1', '系统设置', '图像设置', '彩色设置', '0', '0', '1', '系统设置-音画设置-图像设置-彩色设置-色温', '<SettingItem name=\"SKY_CFG_TV_COLOR_TEMPERATURE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_GAIN_RED', '红色增益', '0', '系统设置', '图像设置', '彩色设置', '0', '0', '2', '系统设置-音画设置-图像设置-彩色设置-红色增益', '<SettingItem name=\"SKY_CFG_CC_GAIN_RED\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_GAIN_GREEN', '绿色增益', '0', '系统设置', '图像设置', '彩色设置', '0', '0', '3', '系统设置-音画设置-图像设置-彩色设置-绿色增益', '<SettingItem name=\"SKY_CFG_CC_GAIN_GREEN\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_GAIN_BLUE', '蓝色增益', '0', '系统设置', '图像设置', '彩色设置', '0', '0', '4', '系统设置-音画设置-图像设置-彩色设置-蓝色增益', '<SettingItem name=\"SKY_CFG_CC_GAIN_BLUE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_FLESH_TONE', '肤色偏好', '0', '系统设置', '图像设置', '彩色设置', '0', '0', '5', '系统设置-音画设置-图像设置-彩色设置-肤色偏好', '<SettingItem name=\"SKY_CFG_FLESH_TONE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_FLESH_HUE', '肤色色调', '0', '系统设置', '图像设置', '彩色设置', '0', '0', '6', '系统设置-音画设置-图像设置-彩色设置-肤色色调', '<SettingItem name=\"SKY_CFG_CC_FLESH_HUE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_BLUE_STRETCH', '蓝电平延伸', '0', '系统设置', '图像设置', '彩色设置', '0', '0', '7', '系统设置-音画设置-图像设置-彩色设置-蓝电平延伸', '<SettingItem name=\"SKY_CFG_CC_BLUE_STRETCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_COLOR_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_SUPER_RESOLUTION', '超解像', '0', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '1', '系统设置-音画设置-图像设置-高级清晰度设置-默认超解像,可改名为：超级4K增补，超级清晰度等', '<SettingItem name=\"SKY_CFG_CC_SUPER_RESOLUTION\" ></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_AI_DEJAGGY', 'AI抗锯齿', '0', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '2', '系统设置-音画设置-图像设置-高级清晰度设置-AI抗锯齿', '<SettingItem name=\"SKY_CFG_AI_DEJAGGY\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_DNR', '降噪', '1', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '3', '系统设置-音画设置-图像设置-高级清晰度设置-默认降噪，可改名为：动态目标重塑', '<SettingItem name=\"SKY_CFG_TV_DNR\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_DE_CONTOUR', '精密平滑处理', '0', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '4', '系统设置-音画设置-图像设置-高级清晰度设置-默认平滑处理，可改名为：精密平滑处理', '<SettingItem name=\"SKY_CFG_CC_DE_CONTOUR\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_DE_BLOCK', '块噪声消除', '0', '系统设置', '图像设置', '高级清晰度设置', '0', '0', '5', '系统设置-音画设置-图像设置-高级清晰度设置-块噪声消除，蚊状噪声消除 两个合并为一个：MPEG降噪', '<SettingItem name=\"SKY_CFG_CC_DE_BLOCK\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_SHARPNESS_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_CC_MEMC', '动态图像校正MEMC', '0', '系统设置', '图像设置', '运动设置', '0', '0', '1', '系统设置-音画设置-图像设置-运动设置-动态图像校正MEMC', '<SettingItem name=\"SKY_CFG_CC_MEMC\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_MOTION_SETTING');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_PICTURE_RESET', '恢复默认值', '1', '系统设置', '图像设置', '恢复默认值', '0', '0', '1', '系统设置-音画设置-图像设置-恢复默认值', '<SettingItem name=\"SKY_CFG_TV_PICTURE_RESET\" type=\"TYPE_DIALOG\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_PICTURE_SETTING', 'SKY_CFG_TV_PICTURE_RESET');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_NEW_EQUALIZER', '新版均衡器', '1', '系统设置', '声音设置', '基础设置', '0', '0', '1', '系统设置-音画设置-声音设置-基础设置-新版均衡器', '<SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER\" type=\"TYPE_CONTAINER\" transparent=\"true\"><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_BASS\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_MIDBASS\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_ALTO\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_ALT\"></SettingItem><SettingItem name=\"SKY_CFG_TV_NEW_EQUALIZER_TREBLE\"></SettingItem></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SURROUND', '环绕声、Atoms音效、DTS音效', '1', '系统设置', '声音设置', '基础设置', '0', '0', '2', '系统设置-音画设置-声音设置-基础设置-环绕声、Atoms音效、DTS音效', '<SettingItem name=\"SKY_CFG_TV_SURROUND\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_INTEL_CONTROL_VOLUME', '智能音量控制', '1', '系统设置', '声音设置', '基础设置', '0', '0', '3', '系统设置-音画设置-声音设置-基础设置-智能音量控制', '<SettingItem name=\"SKY_CFG_TV_INTEL_CONTROL_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SUBWOOFER_VOLUME', '重低音音量', '0', '系统设置', '声音设置', '基础设置', '0', '0', '4', '系统设置-音画设置-声音设置-基础设置-重低音音量', '<SettingItem name=\"SKY_CFG_TV_SUBWOOFER_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SOUND_SPDIF_BOX', 'SPIDF输出（盒子专用）', '0', '系统设置', '声音设置', '基础设置', '0', '0', '5', '系统设置-音画设置-声音设置-基础设置-SPIDF输出（盒子专用）', '<SettingItem name=\"SKY_CFG_TV_SOUND_SPDIF\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_ADJUST_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_AUDIO_OUTPUT', '声音输出', '1', '系统设置', '声音设置', '声音输出设置', '0', '0', '1', '系统设置-音画设置-声音设置-声音输出设置-声音输出', '<SettingItem name=\"SKY_CFG_TV_AUDIO_OUTPUT\" association=\"SKY_CFG_TV_SOUND_SPDIF\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SOUND_SPDIF', 'SPDIF输出', '0', '系统设置', '声音设置', '声音输出设置', '0', '0', '2', '系统设置-音画设置-声音设置-声音输出设置-SPDIF输出,后改名为：数字音频输出', '<SettingItem name=\"SKY_CFG_TV_SOUND_SPDIF\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_BOOT_VIDEO_SOUND_SWITCH', '开机音频输出', '1', '系统设置', '声音设置', '声音输出设置', '0', '0', '3', '系统设置-音画设置-声音设置-声音输出设置-开机音频输出，开始定放通用设置，后来决定放到这里', '<SettingItem name=\"SKY_CFG_TV_BOOT_VIDEO_SOUND_SWITCH\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_GFG_TV_VOICE_DELAY', '声音延时', '0', '系统设置', '声音设置', '声音输出设置', '0', '0', '4', '系统设置-音画设置-声音设置-声音输出设置-声音延时，此功能仅在支持DolbyAtmos的机器上的测试和认证版本体现，量产版本不体现', '<SettingItem name=\"SKY_GFG_TV_VOICE_DELAY\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_INSTALL_MODE', '电视安装方式', '0', '系统设置', '声音设置', '声音输出设置', '0', '0', '5', '系统设置-音画设置-声音设置-电视安装方式,后改名为：声音场景（W8等机器有此项）', '<SettingItem name=\"SKY_CFG_TV_INSTALL_MODE\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_OUTPUT_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_SOUND_EFFECTS', 'ATMOS音效', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '1', '系统设置-音画设置-声音设置-ATMOS专业音效设置-ATMOS音效', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SOUND_EFFECTS\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_DRC', '动态范围控制', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '2', '系统设置-音画设置-声音设置-ATMOS专业音效设置-动态范围控制', '<SettingItem name=\"SKY_CFG_TV_ATMOS_DRC\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_SUBWOOFER_VOLUME', '重低音微调', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '3', '系统设置-音画设置-声音设置-ATMOS专业音效设置-重低音微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SUBWOOFER_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_SCENE_SELECT', '场景选择', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '4', '系统设置-音画设置-声音设置-ATMOS专业音效设置-场景选择', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SCENE_SELECT\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_MAIN_SOUNDTRACK_VOLUME', '主声道微调', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '5', '系统设置-音画设置-声音设置-ATMOS专业音效设置-主声道微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_MAIN_SOUNDTRACK_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_MIDDLE_VOLUME', '中置音量微调', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '6', '系统设置-音画设置-声音设置-ATMOS专业音效设置-中置音量微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_MIDDLE_VOLUME\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_SURROUND_LEFT_VOLUME_ADJUST', '左环绕声微调', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '7', '系统设置-音画设置-声音设置-ATMOS专业音效设置-左环绕声微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SURROUND_LEFT_VOLUME_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_SURROUND_RIGHT_VOLUME_ADJUST', '右环绕声微调', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '8', '系统设置-音画设置-声音设置-ATMOS专业音效设置-右环绕声微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_SURROUND_RIGHT_VOLUME_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_ATMOS_PANORAMIC_VOLUME_ADJUST', '全景音量微调', '0', '系统设置', '声音设置', 'ATMOS专业音效设置', '0', '0', '9', '系统设置-音画设置-声音设置-ATMOS专业音效设置-全景音量微调', '<SettingItem name=\"SKY_CFG_TV_ATMOS_PANORAMIC_VOLUME_ADJUST\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_ATMOS_PROFESSIONAL_SETTINGS');
INSERT INTO `v62_settings` VALUES (null, 'SKY_CFG_TV_SOUND_RESET', '恢复默认值', '1', '系统设置', '声音设置', '恢复默认值', '0', '0', '1', '系统设置-音画设置-声音设置-恢复默认值', '<SettingItem name=\"SKY_CFG_TV_SOUND_RESET\" type=\"TYPE_DIALOG\"></SettingItem>', 'setting_picture_sound.xml', 'SKY_CFG_TV_SOUND_SETTING', 'SKY_CFG_TV_SOUND_RESET');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_PIXEL_CONTROL_LIGHT', '像素控光', '0', '卖场演示', '图像演示', '', '0', '0', '1', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光”演示', '<item type=\"Boolean\" key=\"PIXEL_CONTROL_LIGHT\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_LIMIT_CONTRAST', '像素控光-极限对比', '0', '卖场演示', '图像演示', '', '0', '0', '2', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光-极限对比”演示', '<item type=\"Boolean\" key=\"LIMIT_CONTRAST\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_FAST_RESPONSE', '像素控光-极速响应', '0', '卖场演示', '图像演示', '', '0', '0', '3', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光-极速响应”演示', '<item type=\"Boolean\" key=\"FAST_RESPONSE\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_HDR_BOOST', '像素控光-HDR Boost', '0', '卖场演示', '图像演示', '', '0', '0', '4', '卖场演示-选择开关 - 卖场演示中是否显示“像素控光-HDR Boost”演示', '<item type=\"Boolean\" key=\"HDR_BOOST\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_PRECISE_SMOOTH', '精密平滑处理', '0', '卖场演示', '图像演示', '', '0', '0', '5', '卖场演示-选择开关 - 卖场演示中是否显示“精密平滑处理”演示', '<item type=\"Boolean\" key=\"PRECISE_SMOOTH\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_SquareNr', '动态目标重塑（Square NR）', '0', '卖场演示', '图像演示', '', '0', '0', '6', '卖场演示-选择开关 - 卖场演示中是否显示“动态目标重塑（Square NR）”演示', '<item type=\"Boolean\" key=\"SquareNr\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_SuperDefinitionReshape', '4K极清重塑', '0', '卖场演示', '图像演示', '', '0', '0', '7', '卖场演示-选择开关 - 卖场演示中是否显示“4K极清重塑”演示', '<item type=\"Boolean\" key=\"SuperDefinitionReshape\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_DenoiseMaster', '降噪大师', '0', '卖场演示', '图像演示', '', '0', '0', '8', '卖场演示-选择开关 - 卖场演示中是否显示“降噪大师”演示', '<item type=\"Boolean\" key=\"DenoiseMaster\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_DenoiseMaster', 'AI肤色校准', '0', '卖场演示', '图像演示', '', '0', '0', '9', '卖场演示-选择开关 - 卖场演示中是否显示“AI肤色校准”演示', '<item type=\"Boolean\" key=\"SkinColor_Adjust\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_MicroDimming_Enhance', '区域对比增强', '0', '卖场演示', '图像演示', '', '0', '0', '10', '卖场演示-选择开关 - 卖场演示中是否显示“区域对比增强”演示', '<item type=\"Boolean\" key=\"MicroDimming_Enhance\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_Intelligent_Dynamic_Range', '智能动态范围扩展', '0', '卖场演示', '图像演示', '', '0', '0', '11', '卖场演示-选择开关 - 卖场演示中是否显示“智能动态范围扩展”演示', '<item type=\"Boolean\" key=\"Intelligent_Dynamic_Range\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_SUPER_SHARPNESS', '超级清晰度', '0', '卖场演示', '图像演示', '', '0', '0', '12', '卖场演示-选择开关 - 卖场演示中是否显示“超级清晰度”演示', '<item type=\"Boolean\" key=\"SUPER_SHARPNESS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_SUPER_ONLINE_DNR', '超清在线解析', '0', '卖场演示', '图像演示', '', '0', '0', '13', '卖场演示-选择开关 - 卖场演示中是否显示“超清在线解析”演示', '<item type=\"Boolean\" key=\"SUPER_ONLINE_DNR\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_COLOR_STANDER_CONTROL', '精准色相控制', '0', '卖场演示', '图像演示', '', '0', '0', '14', '卖场演示-选择开关 - 卖场演示中是否显示“精准色相控制”演示', '<item type=\"Boolean\" key=\"COLOR_STANDER_CONTROL\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_COLOR_STANDER', '精准色控', '0', '卖场演示', '图像演示', '', '0', '0', '15', '卖场演示-选择开关 - 卖场演示中是否显示“精准色控”演示', '<item type=\"Boolean\" key=\"COLOR_STANDER\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_LOCAL_DIMMING', 'Local Dimming', '0', '卖场演示', '图像演示', '', '0', '0', '16', '卖场演示-选择开关 - 卖场演示中是否显示“Local Dimming”演示', '<item type=\"Boolean\" key=\"LOCAL_DIMMING\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_FourAxisAntiShakePlus', 'MotionFlow Plus', '0', '卖场演示', '图像演示', '', '0', '0', '17', '卖场演示-选择开关 - 卖场演示中是否显示“MotionFlow Plus”演示', '<item type=\"Boolean\" key=\"FourAxisAntiShakePlus\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_MEMC', '4K MEMC+', '0', '卖场演示', '图像演示', '', '0', '0', '18', '卖场演示-选择开关 - 卖场演示中是否显示“4K MEMC+”演示', '<item type=\"Boolean\" key=\"MEMC\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_GAMMA_IMAGE_CALIBRATION', 'Gamma图像校准', '0', '卖场演示', '图像演示', '', '0', '0', '19', '卖场演示-选择开关 - 卖场演示中是否显示“Gamma图像校准”演示', '<item type=\"Boolean\" key=\"GAMMA_IMAGE_CALIBRATION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_LAP', '无毒广色域', '0', '卖场演示', '图像演示', '', '0', '0', '20', '卖场演示-选择开关 - 卖场演示中是否显示“无毒广色域”演示', '<item type=\"Boolean\" key=\"LAP\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_SOLID_TECH', '纯色技术', '0', '卖场演示', '图像演示', '', '0', '0', '21', '卖场演示-选择开关 - 卖场演示中是否显示“纯色技术”演示', '<item type=\"Boolean\" key=\"SOLID_TECH\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_LAP_HIGH', 'LAP高色域', '0', '卖场演示', '图像演示', '', '0', '0', '22', '卖场演示-选择开关 - 卖场演示中是否显示“LAP高色域”演示', '<item type=\"Boolean\" key=\"LAP_HIGH\" value=\"false\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_DOBLY_VISION', 'Dobly Vision', '0', '卖场演示', '图像演示', '', '0', '0', '23', '卖场演示-选择开关 - 卖场演示中是否显示“Dobly Vision”演示', '<item type=\"Boolean\" key=\"DOBLY_VISION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_HDR_10', 'HDR_10', '0', '卖场演示', '图像演示', '', '0', '0', '24', '卖场演示-选择开关 - 卖场演示中是否显示“HDR-10”演示', '<item type=\"Boolean\" key=\"HDR_10\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_MICRO_DIMMING', '区域对比提升', '0', '卖场演示', '图像演示', '', '0', '0', '25', '卖场演示-选择开关 - 卖场演示中是否显示“区域对比提升”演示', '<item type=\"Boolean\" key=\"MICRO_DIMMING\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_MICRO_DIMMING_PLUS', '区域对比提升进阶版', '0', '卖场演示', '图像演示', '', '0', '0', '26', '卖场演示-选择开关 - 卖场演示中是否显示“区域对比提升进阶版”演示', '<item type=\"Boolean\" key=\"MICRO_DIMMING_PLUS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_OPTICAL_BLUE_RAY', '光学防蓝光', '0', '卖场演示', '图像演示', '', '0', '0', '27', '卖场演示-选择开关 - 卖场演示中是否显示“光学防蓝光”演示', '<item type=\"Boolean\" key=\"OPTICAL_BLUE_RAY\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_LOW_REFLECTION', '低反射', '0', '卖场演示', '图像演示', '', '0', '0', '28', '卖场演示-选择开关 - 卖场演示中是否显示“低反射”演示', '<item type=\"Boolean\" key=\"LOW_REFLECTION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_HIGH_CONTRAST', '高对比', '0', '卖场演示', '图像演示', '', '0', '0', '29', '卖场演示-选择开关 - 卖场演示中是否显示“高对比”演示', '<item type=\"Boolean\" key=\"HIGH_CONTRAST\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_EYE_SAFEMODE', '护眼模式', '0', '卖场演示', '图像演示', '', '0', '0', '30', '卖场演示-选择开关 - 卖场演示中是否显示“护眼模式”演示', '<item type=\"Boolean\" key=\"EYE_SAFEMODE\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_LocalDimmingBoost', '精睿控光', '0', '卖场演示', '图像演示', '', '0', '0', '31', '卖场演示-选择开关 - 卖场演示中是否显示“精睿控光”演示', '<item type=\"Boolean\" key=\"LocalDimmingBoost\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'image');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_SPEAKER_SYSTEM', '音响系统', '0', '卖场演示', '声音演示', '', '0', '0', '1', '卖场演示-选择开关 - 卖场演示中是否显示“音响系统”演示', '<item type=\"Boolean\" key=\"SPEAKER_SYSTEM\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_MAGIC_SOUND_TECH', '魔音技术', '0', '卖场演示', '声音演示', '', '0', '0', '2', '卖场演示-选择开关 - 卖场演示中是否显示“魔音技术”演示', '<item type=\"Boolean\" key=\"MAGIC_SOUND_TECH\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_MAGIC_SOUND_TECH_PLUS', '魔音技术+', '0', '卖场演示', '声音演示', '', '0', '0', '3', '卖场演示-选择开关 - 卖场演示中是否显示“魔音技术+”演示', '<item type=\"Boolean\" key=\"MAGIC_SOUND_TECH_PLUS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_ATMOS', 'ATMOS音效', '0', '卖场演示', '声音演示', '', '0', '0', '4', '卖场演示-选择开关 - 卖场演示中是否显示“ATMOS音效”演示', '<item type=\"Boolean\" key=\"ATMOS\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_DSP', 'DSP智能修正', '0', '卖场演示', '声音演示', '', '0', '0', '5', '卖场演示-选择开关 - 卖场演示中是否显示“DSP智能修正”演示', '<item type=\"Boolean\" key=\"DSP\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_VOLUME_MUTATION', '音量突变保护', '0', '卖场演示', '声音演示', '', '0', '0', '6', '卖场演示-选择开关 - 卖场演示中是否显示“音量突变保护”演示', '<item type=\"Boolean\" key=\"VOLUME_MUTATION\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'MARKET_SHOW_ACCURATE_SOUND', '精准声场定位', '0', '卖场演示', '声音演示', '', '0', '0', '7', '卖场演示-选择开关 - 卖场演示中是否显示“精准声场定位”演示', '<item type=\"Boolean\" key=\"ACCURATE_SOUND\" value=\"true\" />', 'market_show_configuration.xml', 'Config', 'sound');
INSERT INTO `v62_settings` VALUES (null, 'BrightnessEnable', '亮度使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'ContrastEnable', '对比度使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'SaturationEnable', '饱和度使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'SharpnessEnable', '清晰度使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'BacklightEnable', '背光使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'LocalDimmingEnable', '矩阵背光使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DynamicContrastEnable', '动态对比度使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'BlackStretchEnablde', '黑色增强使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'LocalContrastEnable', '区域对比提升使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'ColorTemperatureEnable', '色温使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'WhiteBalanceEnable', '白平衡使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'BlueStretchEnable', '蓝色延伸使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'WCGEnable', '广色域使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'SuperResolutionEnable', '4K增补使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'NoiseReductionEnable', '动态目标重塑使能', '1', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DeContourEnable', '精密平滑处理使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DeBlockEnable', 'DeBlockEnable', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DeMosquitoEnable', 'DeMosquitoEnable', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'EyeCareSwitchEnable', '护眼模式使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DreamPanelEnable', '场景屏变使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'MEMCEnable', '动态图像矫正使能', '0', '中间件', 'PQ', null, '0', '0', '0', null, '', 'panel_common_pq.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'PictureParaUnify', '图像参数分源保存', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'FactoryParaUnify', '工厂菜单参数分源保存', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'SurroundTeck', '声音模式', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DolbyDigitalSupport', 'DolbyDigital解码功能', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'supportCEC', '支持HDMI CEC', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'supportARC', '支持HDMI ARC', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'supportHDR', '支持 HDR', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, '3DPictureSeparate', '3D图像模式独立配置', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, '3DDataSaveOnCutOff', '3D设置断电保存', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, '3DAtuoDetect', '3D自动检测', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'UHDDiplayBySR', '4K源以缩放方式处理', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'ATVRFEnable', 'ATV 通道选择', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DVBCEnable', 'DVBC 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'DTMBEnable', 'DTMB 通道选择', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'CVBS1Enable', 'CVBS1 通道选择', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'CVBS2Enable', 'CVBS2 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'CVBS3Enable', 'CVBS3 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'VGAEnable', 'VGA 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'YPBPR1Enable', 'YPBPR1 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'YPBPR2Enable', 'YPBPR2 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'HDMI1Enable', 'HDMI1 通道选择', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'HDMI2Enable', 'HDMI2 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'HDMI3Enable', 'HDMI3 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'HDMI4Enable', 'HDMI4 通道选择', '0', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'MEDIAEnable', 'MEDIA 通道选择', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, '16To9Enable', '显示模式16:9', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, '4To3Enable', '显示模式4:3', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'FullEnable', '显示模式Full', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'PToPEnable', '显示模式PToP', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'AutoEnable', '显示模式Auto', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'ZoomEnable', '显示模式Zoom', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'SubtitleEnable', '显示模式Subtitle', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'CinemaEnable', '显示模式Cinema', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
INSERT INTO `v62_settings` VALUES (null, 'PanoramaEnable', '显示模式Panorama', '1', '中间件', 'Board', null, '0', '0', '0', null, '', 'panel_common_board.ini', 'type1', 'type2');
